l_f/app_shop/urls.py
from django.urls import path, re_path
from .views import product_list, product_detail

app_name = 'app_shop'


urlpatterns = [
    path('', view=product_list, name='product_list'),
    path('<slug:category_slug>/', view=product_list,
         name='product_list_by_category'),
    # path('<int:product_id>/', view=product_detail, name='product_detail'),
    re_path(r'^(?P<id>\d+)/(?P<slug>[-\w]+)/$',
            view=product_detail, name='product_detail'),
]

l_f/cart/urls.py
from django.urls import re_path, path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    re_path(r'^add/(?P<product_id>\d+)/$', views.cart_add, name='cart_add'),
    re_path(r'^remove/(?P<product_id>\d+)/$',
            views.cart_remove, name='cart_remove'),
]

l_f/l_f/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    
    path('cart/', include('cart.urls')),
    path('orders/', include('orders.urls')),
    path('account/', include('account.urls')),
    path('', include('app_shop.urls')),
]

if settings.DEBUG:

    # import debug_toolbar
    # urlpatterns = [
    #     path('__debug__/', include(debug_toolbar.urls)),
    # ] + urlpatterns

    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

l_f/app_shop/models.py
from django.db import models
from django.urls import reverse


# Create your models here.


class Category(models.Model):

    name = models.CharField(max_length=200, db_index=True)
    slug = models.SlugField(max_length=200, db_index=True, unique=True)

    class Meta:
        ordering = ('name',)
        verbose_name = 'Категория'
        verbose_name_plural = 'Категория'

    def __str__(self):
        return str(self.name)

    def get_absolute_url(self):
        
        """
        Returns the url to access a specific product.
        """

        return reverse('app_shop:product_list_by_category', args=[self.slug])
    
class Tag(models.Model):
    
    tag = models.CharField(max_length=50)
    
    def __str__(self):
        return str(self.tag)


class Product(models.Model):
    category = models.ForeignKey(
        Category, related_name='products', on_delete=models.CASCADE)
    
    tag = models.ManyToManyField(
        Tag, related_name='products', blank=True)
    
    
    name = models.CharField(max_length=200, db_index=True)
    slug = models.CharField(max_length=200, db_index=True)
    
    
    
    image = models.ImageField(upload_to='products/%Y/%m/%d', blank=True)
    description = models.TextField(blank=True)
    
    nut_value = models.CharField(max_length=200, blank=True)
    
    netto = models.IntegerField(default=500)
    price = models.IntegerField(default=0)
    
    stock = models.PositiveIntegerField()
    available = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('name',)
        index_together = (('id', 'slug'),)

    def __str__(self):
        return self.name

    def get_absolute_url(self):

        return reverse('app_shop:product_detail',
                       args=[self.id,  self.slug])

l_f/app_shop/views.py
"""
This module provides the views for the product app.
"""
from django.shortcuts import render, get_object_or_404

from .models import Category, Product
from cart.forms import CartAddProductForm


def product_list(request, category_slug=None):
    """
    Renders the product list view. 

    Args:
        request (HttpRequest): The current request.
        category_slug (str, optional): The slug of the selected category.

    Returns:
        HttpResponse: The rendered product list view.
    """

    category = None
    categories = Category.objects.all()
    products = Product.objects.filter(available=True)
    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        products = products.filter(category=category)
    return render(request,
                  'app_shop/product/list.html',
                  {'category': category,
                   'categories': categories,
                   'products': products})


def product_detail(request, id, slug):
    """
    Renders the product detail view.

    Args:
        request (HttpRequest): The current request.
        id (int): The ID of the product.
        slug (str): The slug of the product.

    Returns:
        HttpResponse: The rendered product detail view.
    """
    product = get_object_or_404(Product,
                                id=id,
                                slug=slug,
                                available=True)
    cart_product_form = CartAddProductForm()
    return render(request, 'app_shop/product/detail.html',
                  {'product': product,
                   'cart_product_form': cart_product_form})

l_f/app_shop/templates/app_shop/product/detail.html
{% extends 'app_shop/base.html' %}
{% load static %}

{% block title %}
  {% if category %}
    {{ category.title }}
  {% else %}
    Products
  {% endif %}
{% endblock %}

{% block content %}
  <h6>категория: <a href="{{ product.category.get_absolute_url }}">{{ product.category }}</a></h6>
  <br />
  <div class="product-detail">
    <img src="{% if product.image %}
        {{ product.image.url }}
      {% else %}
        {% static 'app_shop/no_image.png' %}
      {% endif %}" />
    <h1>{{ product.name }}</h1>
    <!-- <h2><a href="{{ product.category.get_absolute_url }}">{{ product.category }}</a></h2> -->
    <h7 class="price">{{ product.description }}</h7>
    <h6 class="price">Вес: {{ product.netto }}г.</h6>
    <h4 class="price">1шт - {{ product.price }} руб.</h4>

    {% comment %} <a role="button" href="#" class="btn btn-primary px-5">В корзину</a> {% endcomment %}

    <p class="price">${{ product.price }}</p>

    <form action="{% url 'cart:cart_add' product.id %}" method="post">
      {{ cart_product_form }}
      {% csrf_token %}
      <input class="btn btn-primary px-5" type="submit" value="В корзину" />
    </form>
  </div>
{% endblock %}

l_f/app_shop/templates/app_shop/product/modal.html
{% comment %}МОДАЛЬНОЕ ОКНО блок для быстрого просмотра{% endcomment %}
<!-- Quickview Wrapper -->
{% for product in products %}
  <div class="modal" id="{{ product.slug }}" data-animation="slideInUp">
    <div class="modal-dialog quickview__main--wrapper">
      <header class="modal-header quickview__header">
        <button class="close-modal quickview__close--btn" aria-label="close modal" data-close>✕</button>
      </header>

      <div class="quickview__inner">
        <div class="row row-cols-lg-2 row-cols-md-2">
          <div class="col">
            <div class="quickview__gallery">
              <div class="product__media--preview swiper">
                <div class="swiper-wrapper">
                  <div class="swiper-slide">
                    <div class="product__media--preview__items">
                      <a class="product__media--preview__items--link glightbox" data-gallery="product-media-preview" href="{{ product.image.url }}"><img class="product__media--preview__items--img" src="{{ product.image.url }}" alt="product-media-img" /></a>
                      <div class="product__media--view__icon">
                        <a class="product__media--view__icon--link glightbox" href="assets/img/product/big-product/product1.webp" data-gallery="product-media-preview">
                          <svg class="product__items--action__btn--svg" xmlns="http://www.w3.org/2000/svg" width="22.51" height="22.443" viewBox="0 0 512 512">
                            <path d="M221.09 64a157.09 157.09 0 10157.09 157.09A157.1 157.1 0 00221.09 64z" fill="none" stroke="currentColor" stroke-miterlimit="10" stroke-width="32"></path>
                            <path fill="none" stroke="currentColor" stroke-linecap="round" stroke-miterlimit="10" stroke-width="32" d="M338.29 338.29L448 448"></path>
                          </svg>
                          <span class="visually-hidden">product view</span>
                        </a>
                      </div>
                    </div>
                  </div>
                  <div class="swiper-slide">
                    <div class="product__media--preview__items">
                      <a class="product__media--preview__items--link glightbox" data-gallery="product-media-preview" href="assets/img/product/big-product/product2.webp"><img class="product__media--preview__items--img" src="assets/img/product/big-product/product2.webp" alt="product-media-img" /></a>
                      <div class="product__media--view__icon">
                        <a class="product__media--view__icon--link glightbox" href="assets/img/product/big-product/product2.webp" data-gallery="product-media-preview">
                          <svg class="product__items--action__btn--svg" xmlns="http://www.w3.org/2000/svg" width="22.51" height="22.443" viewBox="0 0 512 512">
                            <path d="M221.09 64a157.09 157.09 0 10157.09 157.09A157.1 157.1 0 00221.09 64z" fill="none" stroke="currentColor" stroke-miterlimit="10" stroke-width="32"></path>
                            <path fill="none" stroke="currentColor" stroke-linecap="round" stroke-miterlimit="10" stroke-width="32" d="M338.29 338.29L448 448"></path>
                          </svg>
                          <span class="visually-hidden">product view</span>
                        </a>
                      </div>
                    </div>
                  </div>
                  <div class="swiper-slide">
                    <div class="product__media--preview__items">
                      <a class="product__media--preview__items--link glightbox" data-gallery="product-media-preview" href="assets/img/product/big-product/product3.webp"><img class="product__media--preview__items--img" src="assets/img/product/big-product/product3.webp" alt="product-media-img" /></a>
                      <div class="product__media--view__icon">
                        <a class="product__media--view__icon--link glightbox" href="assets/img/product/big-product/product3.webp" data-gallery="product-media-preview">
                          <svg class="product__items--action__btn--svg" xmlns="http://www.w3.org/2000/svg" width="22.51" height="22.443" viewBox="0 0 512 512">
                            <path d="M221.09 64a157.09 157.09 0 10157.09 157.09A157.1 157.1 0 00221.09 64z" fill="none" stroke="currentColor" stroke-miterlimit="10" stroke-width="32"></path>
                            <path fill="none" stroke="currentColor" stroke-linecap="round" stroke-miterlimit="10" stroke-width="32" d="M338.29 338.29L448 448"></path>
                          </svg>
                          <span class="visually-hidden">product view</span>
                        </a>
                      </div>
                    </div>
                  </div>
                  <div class="swiper-slide">
                    <div class="product__media--preview__items">
                      <a class="product__media--preview__items--link glightbox" data-gallery="product-media-preview" href="{{ product.image.url }}"><img class="product__media--preview__items--img" src="assets/img/product/big-product/product4.webp" alt="product-media-img" /></a>
                      <div class="product__media--view__icon">
                        <a class="product__media--view__icon--link glightbox" href="assets/img/product/big-product/product4.webp" data-gallery="product-media-preview">
                          <svg class="product__items--action__btn--svg" xmlns="http://www.w3.org/2000/svg" width="22.51" height="22.443" viewBox="0 0 512 512">
                            <path d="M221.09 64a157.09 157.09 0 10157.09 157.09A157.1 157.1 0 00221.09 64z" fill="none" stroke="currentColor" stroke-miterlimit="10" stroke-width="32"></path>
                            <path fill="none" stroke="currentColor" stroke-linecap="round" stroke-miterlimit="10" stroke-width="32" d="M338.29 338.29L448 448"></path>
                          </svg>
                          <span class="visually-hidden">product view</span>
                        </a>
                      </div>
                    </div>
                  </div>
                </div>
              </div>

              <div class="product__media--nav swiper">
                <div class="swiper-wrapper">
                  <div class="swiper-slide">
                    <div class="product__media--nav__items">
                      <img class="product__media--nav__items--img" src="assets/img/product/small-product/product2.webp" alt="product-nav-img" />
                    </div>
                  </div>
                  <div class="swiper-slide">
                    <div class="product__media--nav__items">
                      <img class="product__media--nav__items--img" src="assets/img/product/small-product/product2.webp" alt="product-nav-img" />
                    </div>
                  </div>
                  <div class="swiper-slide">
                    <div class="product__media--nav__items">
                      <img class="product__media--nav__items--img" src="assets/img/product/small-product/product3.webp" alt="product-nav-img" />
                    </div>
                  </div>
                  <div class="swiper-slide">
                    <div class="product__media--nav__items">
                      <img class="product__media--nav__items--img" src="assets/img/product/small-product/product3.webp" alt="product-nav-img" />
                    </div>
                  </div>
                  <div class="swiper-slide">
                    <div class="product__media--nav__items">
                      <img class="product__media--nav__items--img" src="assets/img/product/small-product/product4.webp" alt="product-nav-img" />
                    </div>
                  </div>
                </div>
                <div class="swiper__nav--btn swiper-button-next">
                  <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="-chevron-right">
                    <polyline points="9 18 15 12 9 6"></polyline>
                  </svg>
                </div>
                <div class="swiper__nav--btn swiper-button-prev">
                  <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="-chevron-left">
                    <polyline points="15 18 9 12 15 6"></polyline>
                  </svg>
                </div>
              </div>
            </div>
          </div>

          <div class="col">
            <div class="quickview__info">
              <form action="#">
                <h2 class="product__details--info__title mb-10">{{ product.name }}</h2>
                <div class="product__card--price mb-10">
                  <span class="current__price">{{ product.price }} руб.</span>
                  <p class="product__details--info__desc mb-10">{{ product.description }}</p>

                  <div class="quickview__variant--list quantity d-flex align-items-center mb-10">
                    <div class="quantity__box">
                      {% comment %}выбор количества{% endcomment %}
                      <button type="button" class="quantity__value quickview__value--quantity decrease" aria-label="quantity value" value="Decrease Value">-</button>
                      <label><input type="number" class="quantity__number quickview__value--number" value="1" data-counter /></label>
                      <button type="button" class="quantity__value quickview__value--quantity increase" aria-label="quantity value" value="Increase Value">+</button>
                    </div>
                    {% comment %}выбор количества{% endcomment %}

                    <button class="primary__btn quickview__cart--btn" type="submit">Add To Cart</button>
                  </div>
                </div>
              </form>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endfor %}
<!-- Quickview Wrapper End -->