l_f/cart/urls.py
from django.urls import re_path, path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    re_path(r'^add/(?P<product_id>\d+)/$', views.cart_add, name='cart_add'),
    re_path(r'^remove/(?P<product_id>\d+)/$',
            views.cart_remove, name='cart_remove'),
]

l_f/l_f/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    
    path('cart/', include('cart.urls')),
    path('orders/', include('orders.urls')),
    path('account/', include('account.urls')),
    path('', include('app_shop.urls')),
]

if settings.DEBUG:

    # import debug_toolbar
    # urlpatterns = [
    #     path('__debug__/', include(debug_toolbar.urls)),
    # ] + urlpatterns

    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

l_f/cart/forms.py
from django import forms


PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 50)]


class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(choices=PRODUCT_QUANTITY_CHOICES, coerce=int)
    update = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)
    

l_f/cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from app_shop.models import Product
from .cart import Cart
from .forms import CartAddProductForm

# Create your views here.


@require_POST
def cart_add(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    form = CartAddProductForm(request.POST)
    print(form.errors)
    
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product=product,
                 quаntity=cd['quantity'],
                 update_quantity=cd['update'])
    return redirect('cart:cart_detail')

def cart_remove(request, product_id):
    cart = Cart(request)
    product_id = int(product_id)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product=product)
    return redirect('cart:cart_detail')

def cart_detail(request):
    cart = Cart(request)
    context = {'cart': cart}
    return render(request, 'cart/cart_detail.html', context)


# https://pocoz.gitbooks.io/django-v-primerah/content/glava-7-sozdanie-internet-magazina/sozdanie-korzini/sozdanie-predstavlenii-korzini-pokupok/dobavlenie-elementov-v-korzinu.html

l_f/cart/templates/cart/cart_detail.html
{% extends 'app_shop/base.html' %}
{% load static %}

{% block title %}

{% endblock %}
{% block content %}
  <div>
    {% for item in cart %}
      {% with product=item.product %}
        <tr>
          <th scope="row" class="border-0">
            <a href="{{ product.get_absolute_url }}">
              <img src="{% if product.image %}
                  {{ product.image.url }}
                {% else %}
                  {% static 'app_shop/img/no_image.png' %}
                {% endif %}"
                alt=""
                width="70"
                class="img-fluid rounded shadow-sm" />
            </a>
            <div class="ml-3 d-inline-block align-middle">
              <h5 class="mb-0"><a href="#" class="text-dark d-inline-block align-middle">{{ product.name }}</a></h5><span class="text-muted font-weight-normal">{{ product.category }}</span>
            </div>
          </th>
          <td class="border-0 align-middle">
            <strong>{{ item.price }} руб.</strong>
          </td>
          <td class="border-0 align-middle">
            <strong>{{ item.quantity }}</strong>
          </td>
          <td class="border-0 align-middle">
            <a href="{% url 'cart:cart_remove' product.id %}" class="text-dark"><i class="fa fa-trash">удалить</i></a>
          </td>
          <td class="border-0 align-middle">
            <strong>{{ item.total_price }} руб.</strong>
          </td>
        </tr>
      {% endwith %}
    {% endfor %}
  </div>
{% endblock %}