l_f/account/urls.py
from django.urls import path, reverse_lazy
from django.contrib.auth import views as auth_views
from . import views




app_name = 'account'

urlpatterns = [
    # path('login/', views.user_login, name='login')

    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),

    # url-адреса смены пароля
    path('password-change/',
         auth_views.PasswordChangeView.as_view(
             success_url=reverse_lazy('account:password_change_done')),
         name='password_change'),
    path('password-change/done/',
         auth_views.PasswordChangeDoneView.as_view(),
         name='password_change_done'),


    # url-адреса сброса пароля
    path('password-reset/',
         auth_views.PasswordResetView.as_view(
             success_url=reverse_lazy('account:password_reset_done')),
         name='password_reset'),
    path('password-reset/done/',
         auth_views.PasswordResetDoneView.as_view(),
         name='password_reset_done'),
    path('password-reset/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(success_url=reverse_lazy('account:password_reset_complete')),
         name='password_reset_confirm'),
    path('password-reset/complete/',
         auth_views.PasswordResetCompleteView.as_view(),
         name='password_reset_complete'),

    # страница аккаунта в дашборде (то есть страница профиля)
    path('dashboard/', views.dashboard, name='dashboard'),
    path('dashboard/change_profile', views.change_profile, name='change_profile'),
    
    path('register/', views.register, name='register'),


]

l_f/app_shop/urls.py
from django.urls import path, re_path
from .views import product_list, product_detail

app_name = 'app_shop'


urlpatterns = [
    path('', view=product_list, name='product_list'),
    path('<slug:category_slug>/', view=product_list,
         name='product_list_by_category'),
    # path('<int:product_id>/', view=product_detail, name='product_detail'),
    re_path(r'^(?P<id>\d+)/(?P<slug>[-\w]+)/$',
            view=product_detail, name='product_detail'),
]

l_f/cart/urls.py
from django.urls import re_path, path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    re_path(r'^add/(?P<product_id>\d+)/$', views.cart_add, name='cart_add'),
    re_path(r'^remove/(?P<product_id>\d+)/$',
            views.cart_remove, name='cart_remove'),
]

l_f/l_f/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    
    path('cart/', include('cart.urls')),
    path('orders/', include('orders.urls')),
    path('account/', include('account.urls')),
    path('', include('app_shop.urls')),
]

if settings.DEBUG:

    # import debug_toolbar
    # urlpatterns = [
    #     path('__debug__/', include(debug_toolbar.urls)),
    # ] + urlpatterns

    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

l_f/app_shop/models.py
from django.db import models
from django.urls import reverse


# Create your models here.


class Category(models.Model):

    name = models.CharField(max_length=200, db_index=True)
    slug = models.SlugField(max_length=200, db_index=True, unique=True)

    class Meta:
        ordering = ('name',)
        verbose_name = 'Категория'
        verbose_name_plural = 'Категория'

    def __str__(self):
        return str(self.name)

    def get_absolute_url(self):
        
        """
        Returns the url to access a specific product.
        """

        return reverse('app_shop:product_list_by_category', args=[self.slug])
    
class Tag(models.Model):
    
    tag = models.CharField(max_length=50)
    
    def __str__(self):
        return str(self.tag)


class Product(models.Model):
    category = models.ForeignKey(
        Category, related_name='products', on_delete=models.CASCADE)
    
    tag = models.ManyToManyField(
        Tag, related_name='products', blank=True)
    
    
    name = models.CharField(max_length=200, db_index=True)
    slug = models.CharField(max_length=200, db_index=True)
    
    
    
    image = models.ImageField(upload_to='products/%Y/%m/%d', blank=True)
    description = models.TextField(blank=True)
    
    nut_value = models.CharField(max_length=200, blank=True)
    
    netto = models.IntegerField(default=500)
    price = models.IntegerField(default=0)
    
    stock = models.PositiveIntegerField()
    available = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('name',)
        index_together = (('id', 'slug'),)

    def __str__(self):
        return self.name

    def get_absolute_url(self):

        return reverse('app_shop:product_detail',
                       args=[self.id,  self.slug])

l_f/app_shop/views.py
"""
This module provides the views for the product app.
"""
from django.shortcuts import render, get_object_or_404

from .models import Category, Product
from cart.forms import CartAddProductForm


def product_list(request, category_slug=None):
    """
    Renders the product list view. 

    Args:
        request (HttpRequest): The current request.
        category_slug (str, optional): The slug of the selected category.

    Returns:
        HttpResponse: The rendered product list view.
    """

    category = None
    categories = Category.objects.all()
    products = Product.objects.filter(available=True)
    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        products = products.filter(category=category)
    return render(request,
                  'app_shop/product/list.html',
                  {'category': category,
                   'categories': categories,
                   'products': products})


def product_detail(request, id, slug):
    """
    Renders the product detail view.

    Args:
        request (HttpRequest): The current request.
        id (int): The ID of the product.
        slug (str): The slug of the product.

    Returns:
        HttpResponse: The rendered product detail view.
    """
    product = get_object_or_404(Product,
                                id=id,
                                slug=slug,
                                available=True)
    cart_product_form = CartAddProductForm()
    return render(request, 'app_shop/product/detail.html',
                  {'product': product,
                   'cart_product_form': cart_product_form})

l_f/app_shop/templates/app_shop/base_bck.html
<!DOCTYPE html>
{% load static %}
{% load compress %}



<html lang="ru">
  <head>
    {% block title %}
    <title>Partsix - Auto Parts & Car Accessories Shop HTML Template</title>
    {% endblock %}

    {% block title_meta %}
    <meta charset="utf-8" />
    <meta name="description" content="Morden Bootstrap HTML5 Template" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="yandex-verification" content="5fccdfbbfd32f5b2" />
    {% endblock %}

    <!-- ======= All CSS Plugins here ======== -->
    <link rel="stylesheet" href="{% static 'app_shop/css/swiper-bundle.min.css' %}" />
    <link rel="stylesheet" href="{% static 'app_shop/css/glightbox.min.css' %}" />
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700;800;900&family=Open+Sans:ital,wght@0,300;0,400;0,500;0,600;0,700;0,800;1,300;1,400;1,500;1,600;1,700&family=Rubik:ital,wght@0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,300;1,400;1,500&display=swap" rel="stylesheet" />

    <link rel="icon" href="{% static 'app_shop/img/favicon.ico' %}" type="image/x-icon" />

    <!-- Plugin css -->
    <link rel="stylesheet" href="{% static 'app_shop/css/bootstrap.min.css' %}">

    <!-- Custom Style CSS -->

    {% comment %} <link rel="stylesheet" href="assets/css/style.css"> {% endcomment %}

    {% compress css %}
      <link type="text/x-scss" href="{% static 'app_shop/scss/style.scss' %}" rel="stylesheet" media="screen">
    {% endcompress %}


</head>



<body>
  <a href="/">ГЛАВНАЯ</a>

  <div class="container pt-4">
    <div class="top_line row bg-light shadow border rounded p-3">
      <div class="session_cart col-6">
        {% with total_items=cart|length %}
          {% if cart|length > 0 %}
            <h5>Корзина:</h5>
            <a href="{% url 'cart:cart_detail' %}">{{ total_items }} шт., на {{ cart.get_total_price }} руб.</a>
          {% else %}
            Ваша корзина пуста.
          {% endif %}
        {% endwith %}
      </div>
    <div class="user_info col-6">
      <span class="logo">Аккаунт</span>
      {% if request.user.is_authenticated %}
      <ul class="menu">
        <li {% if section == "dashboard" %} class="selected" {% endif %}>
        <a href="{% url 'account:dashboard' %}">Личный кабинет</a>
        </li>
      </ul>
      {% endif %}


      <span class="user">
      {% if request.user.is_authenticated %}
      {{ request.user.first_name|default:request.user.username }},
        <a href="{% url 'account:logout' %}">Выйти</a>
      {% else %}
        <a href="{% url 'account:register' %}">Регистрация</a>
        <a href="{% url 'account:login' %}">Войти</a>
      {% endif %}
      </span>
    </div>
  </div>
</div>


{% if messages %}
<ul class="messages">
  {% for message in messages %}
  <li class="{{ message.tags }}">
  {{ message|safe }}
  <a href="#" class="close">x</a>
  </li>
  {% endfor %}
</ul>
{% endif %}


  <div class="container pt-4">
    <div class="top_line row bg-light shadow border d-flex justify-content-center align-items-center rounded p-3">
      <div id="content">
        {% block content %}

        {% endblock %}
      </div>
    </div>
  </div>
  
</body>
</html>